--	SQL Server Data Tools for Visual Studio
--	https://visualstudio.microsoft.com/vs/features/ssdt/
--	Create SQL Server Database Project With Visual Studio
--	https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/ff678491(v=vs.100)?redirectedfrom=MSDN
--	Creating a Visual Studio Database Project for an existing SQL Server Database
--	https://www.mssqltips.com/sqlservertip/2971/creating-a-visual-studio-database-project-for-an-existing-sql-server-database/
--	Create a database and add tables in Visual Studio
--	https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-sql-database-by-using-a-designer?view=vs-2019